project:
  type: website
  resources:
    - "QUARTO/images/**"

website:
  title: ""
  favicon: QUARTO/images/SCOPElogo.png
  page-footer: |
    <div class="footer-logos">
      <img src="/QUARTO/images/LEAP/LEAP_Logo_Red-300.png    " alt="LEAP">
      <img src="/QUARTO/images/LEAP/EPSRC.png"             alt="EPSRC">
    </div>
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: "#0b2b42"
    foreground: "#bec0c1" 
    tools:
      - icon: github
        menu: 
          - text: Source code for site
            href: https://github.com/AliHarp/SCOPE
          - text: Code for literature analyis
            href: https://github.com/pythonhealthdatascience/scope_wsc_2025
            aria-label: GitHub
      - icon: linkedin
        menu:
          - text: LEAP Digital Health Hub
            href: https://www.linkedin.com/showcase/leap-dh-hub/posts/?feedView=all        
            
    logo: QUARTO/images/SCOPE.png
    right:
      - href: index.qmd
        text: "{{< fa house title='HOME' >}}HOME"
      - text: "{{< fa circle-info title='ABOUT' >}}ABOUT"
        href: about.qmd
        
  sidebar:
    style: "docked"
    background: "#fee8e7"
    contents:
      - text: "Literature: Orthopaedic modelling"   
        href: QUARTO/topicmodel.qmd 
format:
  html:
    theme:
      light: styles.scss
    toc: true
    toc-location: right-body
    number-sections: false
    number-depth: 3
    freeze: auto
    page-layout: full
    grid:
      sidebar-width: 400px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem  

editor: visual

